=== raffaeleragni/android-commander/doc/schema.xsd
<?xml version="1.0"?>
<!--
 *   commander - android app for remote and batch command execution
 *   Copyright (C) 2012 Raffaele Ragni
 *   https://github.com/raffaeleragni/android-wardrive4
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *   
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!-- Schema for commander android app. -->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="commander">
        <xs:annotation>
            <xs:documentation>Root element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="command" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="command">
        <xs:annotation>
            <xs:documentation>A batch command to execute</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" minOccurs="1" maxOccurs="1" type="xs:string"/>
                <xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="target" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="command-string" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="command-script-location" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="icon-location" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="private-key-location" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="private-key-passphrase" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="login-username" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="login-password" minOccurs="0" maxOccurs="1" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="risk" type="command-risk" use="required"/>
            <xs:attribute name="type" type="command-type" use="required"/>
            <xs:attribute name="auth" type="command-auth" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="command-risk">
        <xs:annotation>
            <xs:documentation>
                The risk of the command.
                0 = no confirmation,
                1 = normal confirmation (ok/cancel),
                2 = complex confirmation
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="confirm"/>
            <xs:enumeration value="dangerous"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="command-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ssh"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="command-auth">
        <xs:restriction base="xs:string">
            <xs:enumeration value="login"/>
            <xs:enumeration value="privatekey"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== raffaeleragni/android-commander/doc/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<commander xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
           xsi:noNamespaceSchemaLocation='schema.xsd'>
    
    <command type="ssh" auth="private-key" risk="confirm">
        <name>Shutdown server X</name>
        <description>Shuts down the X server through SSH halt command</description>
        <target>10.0.0.2</target>
        <command><![CDATA[sudo halt]]></command>
        <icon-location>icons/shutdown_X.png</icon-location>
        <private-key-location>keys/mypk</private-key-location>
        <private-key-passphrase>bingo</private-key-passphrase>
        <login-username>user</login-username>
    </command>
    
</commander>
